#MODEL:
model_name: tentwo5_decoderdown32
model_type: experimental2
num_classes: 19
ignore_value: 255
pretrained_backbone: False

#OPTIM:
epochs: 500
max_epochs: 500
resume: False
lr: 0.05
momentum: 0.9
weight_decay: 0.0001
class_weight: null
bn_weight_decay: False
bn_precise_stats: False
bn_precise_num_samples: 600
lr_scheduler: poly
poly_power: 0.9
warmup_iters: 3000
warmup_factor: 0.1

#TRAIN:
mixed_precision: True
runs: 1
run: 1
RNG_seed: 0
loss_type: OHEM
eval_while_train: True
exclude_classes: [14,15,16]
cuda: '0'

#benchmark
warmup_iter: 10
num_iter: 100
benchmark_loader: True
benchmark_model: True

#dataset
dataset_name: cityscapes
dataset_dir: cityscapes_dataset
batch_size: 8
train_min_size: 400
train_max_size: 1600
train_crop_size: [768,768]
val_input_size: 1024
val_label_size: 1024
aug_mode: randaug_reduced
resize_mode: uniform
edge_aware_crop: False
boost_rare_classes: False
num_workers: 6
class_uniform_pct: 0.5
train_split: train
val_split: val
max_eval: 600
validate_train_loader: False
eval_print_every: 10000
train_print_every: 10000

#checkpoint  
log_path: './log_file/DW_tentwo5_1'
save_best_path: './pth_file/best_DW_tentwo5_1.pth'
save_latest_path: './pth_file/latest.pth'
pretrained_path: ''

save_every_k_epochs: 25
save_last_k_epochs: 30
#save_dir: checkpoints
#log_dir: training_log
#save_name: cityscapes_exp48_decoder26_1000_epoch_change
